### ISSUE TITLE
Local logging 

### ISSUE THREAD

**Issue by kb0thn** [aprsworld/wsBroadcast#16]
We need to have log local built in to the server.

It should work like this:
if logging is enabled, then append (or create) a file named "YYYYMMDD.json"
Record all data received via TCP or UDP to this file. Flush file after each line. File will be a bunch of JSON arrays, presumably.

**Comment by kb0thn** [comment]
Kind of like a CSV file ... but JSON.

**Comment by davarus** [comment]
Add an argument '-l [directory]' to specify where to store the log files and if the argument is not present, don't log.

**Comment by davarus** [comment]
Implemented sans argument to specify directory in eff3bfe7d1ed18f19efea7321304e3847f9b6d0b.  Closing as the argument handling falls under issue #4.
