### ISSUE TITLE
may not be reconnecting when resuming from hiberate

### ISSUE THREAD

**Issue by kb0thn** [aprsworld/wsBroadcast#18]
On my windows 7 / firefox it was showing connected after I resumed from hibernation. But wasn't updating camera image. Didn't do any further work ... may not be an issue ... maybe camera crashed or something. I will try to get more details if I see it again.

**Comment by kb0thn** [comment]
![capture_frozen](https://cloud.githubusercontent.com/assets/7605226/9288938/cd33bd84-4324-11e5-957c-db3e41813ce2.PNG)

Note time on web display and local time (we are UTC - 5 or UTC - 6 hours)

Reload page and it works fine.

**Comment by kb0thn** [comment]
definitely is never re-connecting when I resume from hibernate. Always have to hit reload to get it going again.

**Comment by davarus** [comment]
Can you confirm if this has been fixed @kb0thn?
