### ISSUE TITLE
location of resources

### ISSUE THREAD

**Issue by kb0thn** [aprsworld/wsBroadcast#27]
Need resources to be local so that system will work when not connected to internet. So instead of http://cam.aprsworld.com:8888/path/to/foo it should be /path/to/foo

Also need defines for magic locations. For instance the web socket host and port and hard coded. That should be defined somehow so the thing can be setup just by modifying some stuff at the top of the file or in its own stand alone file.

**Comment by Cdetviler** [comment]
issue fixed with latest commit
